spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Worldking123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.static-locations=classpath:/static/,file:upload/
# 允許最大 10MB 檔案
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# Gmail SMTP 設定
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=l738451@gmail.com
spring.mail.password=zdhs hpmj gcvz xhsr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true  # 啟用 SMTP debug

# 確保郵件編碼正確
spring.mail.default-encoding=UTF-8

# 允許前端攜帶 Cookie（開發用）
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

# === 強制關閉 Redis（內建 Session）===
# spring.data.redis.host=localhost
# spring.data.redis.port=6379
# spring.session.store-type=redis
# spring.session.timeout=30m

# 完全關閉 Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration